Support building for additional remote origins (#122)
## Motivation for the change, related issues

Since we are running a Playground instance for A8C, we want to be able
to build `@wp-playground/client` to support that remote origin.

This PR:
- Supports specifying additional supported remote Playground origins
during build
- Updates the A8C package-for-self-hosting workflow to build
`@wp-playground/client` to support the origin
`https://wordpress-playground.atomicsites.blog`

## Implementation details

This PR:
- Adds an `additional-remote-origins.ts` module with a default empty
origin list.
- Adds a build-time to the Vite config to replace this module with a
custom list of origins specified via the ADDITIONAL_REMOTE_ORIGINS
environment variable.
- Defines the ADDITIONAL_REMOTE_ORIGINS environment variable in the
package-for-self-hosting workflow.

## Testing Instructions (or ideally a Blueprint)

- CI
- Test locally
- Run `ADDITIONAL_REMOTE_ORIGINS=https://test-this-pr npx nx build
playground-client`
- Grep `dist/packages/playground/client` for
"https://test-this-pr,http://another-remote-origin"
- Note that the origins are added to the built script as separate
strings in an array
- Run `ADDITIONAL_REMOTE_ORIGINS=this-origin-is-invalid nx build
playground-client`
    - Note that there is a build error due to invalid origin

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -138,7 +138,13 @@ jobs:
               with:
                   submodules: true
             - uses: ./.github/actions/prepare-playground
-            - run: npx nx affected --target=build --parallel=3 --verbose
+            - run: |
+                  if ADDITIONAL_REMOTE_ORIGINS=invalid-origin npx nx build playground-client; then
+                    echo "The Playground client build should have failed due to an invalid additional origin."
+                    echo "The build does not appear to be applying ADDITIONAL_REMOTE_ORIGINS."
+                    exit 1
+                  fi
+                  npx nx affected --target=build --parallel=3 --verbose
 
     # Deploy documentation job
     deploy_docs:
